apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: python-client-sa
      containers:
      - name: autoscaler
        image: autoscaler:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"