apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-deployment
  labels:
    app: dispatcher
spec:
  replicas: 1  # Single replica to avoid state issues with in-memory queue
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: dispatcher-app:latest
        imagePullPolicy: IfNotPresent  # Change to Always for production
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: ML_SERVICE_URL
          value: "http://ml-app-service:8000"
        - name: PORT
          value: "8001"
        - name: PYTHONUNBUFFERED
          value: "1"  # Important for logs in K8s
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"  # Increased for image processing
            cpu: "2"       # Increased for 4 workers + FastAPI
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher
spec:
  type: ClusterIP
  selector:
    app: dispatcher
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http